// <auto-generated />
namespace MusicApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class MusicUserApp1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MusicUserApp1));
        
        string IMigrationMetadata.Id
        {
            get { return "202602011207247_MusicUserApp1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
